// Import the 'jsonwebtoken' library to create JSON Web Tokens for authenticated users
const jwt = require('jsonwebtoken'); // Require the 'jsonwebtoken' module and assign it to the constant 'jwt'

// Import the User model to create and authenticate users in the database
const User = require('../models/User'); // Require the '../models/User' module and assign it to the constant 'User'

// Define a helper function to generate a signed JWT token for a given user ID
const generateToken = (userId) => { // Declare a function named 'generateToken' that accepts a single parameter 'userId'
  // Use jwt.sign to create a token containing the user's ID as payload, signed with the secret and expiration from environment variables
  return jwt.sign( // Return the token generated by jwt.sign
    { id: userId }, // Set the payload of the token to an object containing the user's ID
    process.env.JWT_SECRET, // Use the secret key stored in the environment variable JWT_SECRET to sign the token
    { expiresIn: process.env.JWT_EXPIRES_IN || '7d' } // Set the token expiration to JWT_EXPIRES_IN or default to 7 days
  ); // End of jwt.sign call
}; // End of generateToken helper function definition

// Controller to handle user registration at POST /api/auth/register
const registerUser = async (req, res) => { // Declare an async controller function named 'registerUser' with req and res parameters
  try { // Start a try block to handle any synchronous or asynchronous errors gracefully
    // Destructure the required fields from the request body
    const { name, email, password, role } = req.body; // Extract 'name', 'email', 'password', and 'role' from req.body

    // Validate that all required fields are provided (name, email, and password)
    if (!name || !email || !password) { // Check if any of the required fields are missing
      // Return a 400 Bad Request response indicating that all fields are mandatory
      return res.status(400).json({ message: 'Name, email, and password are required' }); // Send a JSON error message to the client
    } // End of required fields validation

    // Check if a user with the same email already exists in the database
    const existingUser = await User.findOne({ email }); // Query the User collection for a document with the given email

    // If an existing user is found, prevent duplicate registration and return an error
    if (existingUser) { // Check whether 'existingUser' is truthy, indicating an email conflict
      // Return a 400 Bad Request response indicating the email is already registered
      return res.status(400).json({ message: 'Email is already registered' }); // Send a JSON error message to the client
    } // End of existing user check

    // Create a new user document with the provided data; password hashing occurs in the User model pre-save hook
    const user = await User.create({ name, email, password, role }); // Use User.create to insert a new user into the database

    // Generate a JWT token for the newly registered user using their unique ID
    const token = generateToken(user._id); // Call generateToken with the new user's ID and store the result in 'token'

    // Return a 201 Created response with the user's public data and the authentication token
    return res.status(201).json({ // Send a JSON response with status code 201 to indicate resource creation
      message: 'User registered successfully', // Provide a success message indicating registration succeeded
      user: { // Include a nested 'user' object containing non-sensitive user fields
        id: user._id, // Include the user's unique MongoDB ObjectId as 'id'
        name: user.name, // Include the user's name field
        email: user.email, // Include the user's email field
        role: user.role, // Include the user's role field
      }, // End of public user object
      token, // Include the generated JWT token so the client can authenticate subsequent requests
    }); // End of JSON response for successful registration
  } catch (error) { // Catch block to handle any errors thrown during registration logic
    // Log the error to the server console for diagnostics and debugging
    console.error('Register user error:', error.message); // Output the error message indicating registration failure
    // Return a 500 Internal Server Error response indicating something went wrong on the server
    return res.status(500).json({ message: 'Server error during registration' }); // Send a generic JSON error message to the client
  } // End of try-catch block for registration controller
}; // End of registerUser controller function definition

// Controller to handle user login at POST /api/auth/login
const loginUser = async (req, res) => { // Declare an async controller function named 'loginUser' with req and res parameters
  try { // Start a try block to handle errors that may occur during login logic
    // Destructure the email and password fields from the request body
    const { email, password } = req.body; // Extract 'email' and 'password' from req.body

    // Validate that both email and password have been provided
    if (!email || !password) { // Check if either email or password is missing
      // Return a 400 Bad Request response indicating that both fields are required
      return res.status(400).json({ message: 'Email and password are required' }); // Send a JSON error message to the client
    } // End of email and password presence check

    // Retrieve the user from the database based on the provided email
    const user = await User.findOne({ email }); // Query the User collection for a document with the given email

    // If no user was found, return an authentication failure response without revealing which field is incorrect
    if (!user) { // Check whether 'user' is falsy, indicating no matching email
      // Return a 401 Unauthorized response indicating invalid credentials
      return res.status(401).json({ message: 'Invalid email or password' }); // Send a generic JSON error message for security
    } // End of user existence check

    // Use the model's matchPassword method to compare the provided password with the stored hashed password
    const isMatch = await user.matchPassword(password); // Call user.matchPassword with the provided password and await the boolean result

    // If the password does not match, return an authentication failure response
    if (!isMatch) { // Check whether 'isMatch' is falsy, indicating a password mismatch
      // Return a 401 Unauthorized response indicating invalid credentials
      return res.status(401).json({ message: 'Invalid email or password' }); // Send a generic JSON error message for security
    } // End of password match check

    // Generate a JWT token for the authenticated user using their unique ID
    const token = generateToken(user._id); // Call generateToken with the authenticated user's ID and store the result in 'token'

    // Return a 200 OK response with the user's public data and the authentication token
    return res.status(200).json({ // Send a JSON response with status code 200 indicating successful login
      message: 'Login successful', // Provide a success message indicating login succeeded
      user: { // Include a nested 'user' object containing non-sensitive user fields
        id: user._id, // Include the user's unique MongoDB ObjectId as 'id'
        name: user.name, // Include the user's name field
        email: user.email, // Include the user's email field
        role: user.role, // Include the user's role field
      }, // End of public user object
      token, // Include the generated JWT token for the client to authenticate subsequent requests
    }); // End of JSON response for successful login
  } catch (error) { // Catch block to handle any errors thrown during login logic
    // Log the error to the server console for diagnostics and debugging
    console.error('Login user error:', error.message); // Output the error message indicating login failure
    // Return a 500 Internal Server Error response indicating something went wrong on the server
    return res.status(500).json({ message: 'Server error during login' }); // Send a generic JSON error message to the client
  } // End of try-catch block for login controller
}; // End of loginUser controller function definition

// Export the authentication controller functions so they can be used in route definitions
module.exports = { registerUser, loginUser }; // Assign an object containing 'registerUser' and 'loginUser' to module.exports

